version: "3.7"

services:
  nginx:
    depends_on:
      - client
    restart: always
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - frontend
    
  client:
    container_name: bitly-front-app
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - "./client/:/app"
      - "/app/node_modules"
    networks:
      - frontend

networks: 
  frontend:
    driver: bridge